#!/usr/bin/env ruby

require 'thor'
require_relative 'installer/vim/vim'
require_relative 'installer/symlinks'
require_relative 'installer/programs/programs'

class Dotfiles < Thor
  desc 'Install the dotfiles', ''
  method_options :compile => :boolean
  def install(owner_directory = nil)
    owner_directory = File.expand_path '~' if owner_directory == nil

    Symlinks.new(owner_directory).install!
    Programs::Programs.new.install!
    Vim::Vim.new(owner_directory, options[:compile]).install!
  end
end

Dotfiles.start(ARGV)
