#!/usr/bin/env ruby

require "thor"
require "./installer/VimDirectory.rb"

class MyCLI < Thor
  desc "hello NAME", "say hello to NAME"
  def install(owner_directory = nil)
      if owner_directory == nil
        owner_directory = File.expand_path '~'
      end

      vimDirectory = VimDirectory.new owner_directory
      vimDirectory.createSymlinks
  end
end

MyCLI.start(ARGV)
