---
directories:
  - '~/.config'
  - '~/.config/dotfiles'
  - '~/.config/nvim'
  - '~/.config/nvim/bak'
  - '~/.config/nvim/tmp'

symlinks:
  - original: './files/zshrc_extension'
    destination: '~/.dotfilesrc'

  - original: './files/gitignore_global'
    destination: '~/.gitignore_global'

  - original: './files/global_ag_ignore'
    destination: '~/.ag_ignore'

  # Nvim config
  - original: './files/vim/init.vim'
    destination: '~/.config/nvim/init.vim'

  - original: './files/vim/plugins.vim'
    destination: '~/.config/nvim/plugins.vim'

  - original: './files/vim/colors'
    destination: '~/.config/nvim/colors'

  - original: './files/vim/snippets'
    destination: '~/.config/nvim/snippets'

  - original: './files/vim/ftplugin'
    destination: '~/.config/nvim/ftplugin'

  # Ideavim config
  - original: './files/vim/ideavim'
    destination: '~/.ideavimrc'
