---
directories:
  - '~/.vim'
  - '~/.vim/bak'
  - '~/.vim/tmp'
  - '~/.vim/bundle'
  - '~/.config'
  - '~/.config/nvim'
  - '~/.config/nvim/autoload'

symlinks:
  - original: './files/vim/config.vim'
    destination: '~/.vimrc'

  - original: './files/vim/colors'
    destination: '~/.vim/colors'

  - original: './files/vim/snippets'
    destination: '~/.vim/snippets'

  - original: './files/vim/ftplugin'
    destination: '~/.vim/ftplugin'

  - original: './files/vim/plugins.vim'
    destination: '~/.vim/plugins.vim'

  - original: './files/global_ag_ignore'
    destination: '~/.ag_ignore'

  - original: './files/nvim/init.vim'
    destination: '~/.config/nvim/init.vim'

  - original: './files/nvim/plugins.vim'
    destination: '~/.config/nvim/plugins.vim'

  - original: './files/vim/colors'
    destination: '~/.config/nvim/colors'

