---
taps:
  - 'universal-ctags/universal-ctags'

packages:
  - executable: 'mysql'
    name: 'mysql'

  - executable: 'ctags'
    name: '--HEAD universal-ctags'

    # Required to build youcompleteme
  - executable: 'cmake'
    name: 'cmake'

  - executable: 'ag'
    name: 'the_silver_searcher'

  - executable: 'phpctags'
    name: 'phpctags'

  - executable: 'rmtrash'
    name: 'rmtrash'

  - executable: 'zsh'
    name: 'zsh zsh-completions'

  - executable: 'nvim'
    name: 'neovim'

  - executable: 'pip3'
    name: 'python3'

  - executable: 'fzf'
    name: 'fzf'
    post_command: '$(brew --prefix)/opt/fzf/install'

  - executable: 'rbenv'
    name: 'rbenv'
    post_command: 'rbenv init'

  - executable: 'php'
    name: 'php'

  - executable: 'composer'
    name: 'composer'

  - executable: 'carthage'
    name: 'carthage'

  - executable: 'htop'
    name: 'htop'

  - executable: 'mix'
    name: 'elixir'
