---
taps:
  - 'homebrew/homebrew-php'
  - 'universal-ctags/universal-ctags'

packages:
  - executable: 'ctags'
    name: '--HEAD universal-ctags'

  - executable: 'ag'
    name: 'the_silver_searcher'

  - executable: 'phpctags'
    name: 'phpctags'

  - executable: 'rmtrash'
    name: 'rmtrash'

  - executable: 'zsh'
    name: 'zsh zsh-completions'

  - executable: 'nvim'
    name: 'neovim'

  - executable: 'pip3'
    name: 'pyhton3'
