---
packages:
  - executable: 'ag'
    name: 'the_silver_searcher'

  - executable: 'nvim'
    name: 'neovim'

  - executable: 'pip3'
    name: 'python3'

  - executable: 'fzf'
    name: 'fzf'
    post_command: '$(brew --prefix)/opt/fzf/install'

  - executable: 'htop'
    name: 'htop'
