---
- executable: 'ag'
  name: 'the_silver_searcher'

- executable: 'fzf'
  name: 'fzf'
  post_command: 'yes | $(brew --prefix)/opt/fzf/install'

- executable: 'gpg'
  name: 'gpg'

- executable: 'htop'
  name: 'htop'

- executable: 'npm'
  name: 'node'

- executable: 'nvim'
  name: 'neovim'

- executable: 'pyenv'
  name: 'pyenv'

- executable: 'redis-cli'
  name: 'redis'

- executable: 'sqlite3'
  name: 'sqlite'

- executable: 'wget'
  name: 'wget'

- executable: 'wrk'
  name: 'wrk'

- executable: 'ctags'
  name: 'ctags'

- executable: 'rg'
  name: 'ripgrep'

- executable: 'fd'
  name: 'fd'

- executable: 'shadowenv'
  name: 'shadowenv'

- executable: 'gmake'
  name: 'make'
