#########
#Aliases#
#########

#System
alias t="tree -L 1"
alias updatedb="sudo /usr/libexec/locate.updatedb"
# alias vim="mvim -v"

#Git
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

#Vim
alias phptags="ctags --languages=PHP -R --exclude=\"\.git\" --totals=yes --tag-relative=yes --PHP-kinds=+cdf"
